/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui.MainGui;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import Runner.MainRunner;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author Mason Smith
 */
@SuppressWarnings("serial")
public class AdminMainGui extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public AdminMainGui() {
    	setTitle("MainMenu");
        initComponents();
        setUpHintText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	//sets the location of frame to middle of screen
    	GraphicsDevice gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
    	this.setLocation(gd.getDisplayMode().getWidth()/4-this.getSize().width/2, gd.getDisplayMode().getHeight()/4-this.getSize().height/2);
    	
        jPanel2 = new javax.swing.JPanel();
        PanelWorkOrder = new javax.swing.JPanel();
        PanelWorkOrder.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent arg0) {
        		MainRunner.runWorkOrderMain();
        		//finds current frame out of listed frames and disposes of it
        		for(int i = 0; i < Frame.getFrames().length; i++) {
        			System.out.println(Frame.getFrames()[i].getTitle());
        			if(Frame.getFrames()[i].getTitle().equals("MainMenu")) {
        				Frame.getFrames()[i].dispose();
        			}
        			
        		}
        	}
        });
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setIcon(new ImageIcon(AdminMainGui.class.getResource("/Resources/workorder-icon.png")));
        jLabel1.setVerticalTextPosition(jLabel1.TOP);
        jLabel1.setHorizontalTextPosition(jLabel1.CENTER);
        RightMenu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        PanelWorkInProgress = new javax.swing.JPanel();
        workinprogress = new javax.swing.JLabel();
        workinprogress.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent arg0) {
        		MainRunner.runworkInProgressMain();
        		//finds current frame out of listed frames and disposes of it
        		for(int i = 0; i < Frame.getFrames().length; i++) {
        			if(Frame.getFrames()[i].getTitle().equals("MainMenu")) {
        				Frame.getFrames()[i].dispose();
        			}
        		}
        	}
        });
        workinprogress.setIcon(new ImageIcon(AdminMainGui.class.getResource("/Resources/workinprogress-icon.png")));
        workinprogress.setHorizontalAlignment(SwingConstants.CENTER);
        workinprogress.setBackground(new Color(240, 240, 240));
        workinprogress.setVerticalTextPosition(workinprogress.TOP);
        workinprogress.setHorizontalTextPosition(workinprogress.CENTER);
        PanelCard = new javax.swing.JPanel();
        PanelCard.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		MainRunner.runCardMain();
        		//finds current frame out of listed frames and disposes of it
        		for(int i = 0; i < Frame.getFrames().length; i++) {
        			if(Frame.getFrames()[i].getTitle().equals("MainMenu")) {
        				Frame.getFrames()[i].dispose();
        			}
        		}
        	}
        });
        Cards = new javax.swing.JLabel();
        Cards.setIcon(new ImageIcon(AdminMainGui.class.getResource("/Resources/idcard-icon.png")));
        Cards.setVerticalTextPosition(Cards.TOP);
        Cards.setHorizontalTextPosition(Cards.CENTER);
        jPanel3 = new javax.swing.JPanel();
        PanelEmployee = new javax.swing.JPanel();
        PanelEmployee.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent arg0) {
        		MainRunner.runEmployeeMain();
        		//finds current frame out of listed frames and disposes of it
        		for(int i = 0; i < Frame.getFrames().length; i++) {
        			if(Frame.getFrames()[i].getTitle().equals("MainMenu")) {
        				Frame.getFrames()[i].dispose();
        			}
        		}
        	}
        });
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setIcon(new ImageIcon(AdminMainGui.class.getResource("/Resources/employee-icon.png")));
        jLabel2.setVerticalTextPosition(jLabel2.TOP);
        jLabel2.setHorizontalTextPosition(jLabel2.CENTER);
        PanelExtra = new javax.swing.JPanel();
        PanelExtra.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent arg0) {
        		MainRunner.runExtraMain();
        		//finds current frame out of listed frames and disposes of it
        		for(int i = 0; i < Frame.getFrames().length; i++) {
        			if(Frame.getFrames()[i].getTitle().equals("MainMenu")) {
        				Frame.getFrames()[i].dispose();
        			}
        		}
        	}
        });
        Extra = new javax.swing.JLabel();
        Extra.setIcon(new ImageIcon(AdminMainGui.class.getResource("/Resources/extra-icon.png")));

        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(960, 540));

        jPanel2.setMinimumSize(new java.awt.Dimension(960, 540));
        jPanel2.setPreferredSize(new java.awt.Dimension(960, 540));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        PanelWorkOrder.setBackground(new java.awt.Color(114, 137, 218));
        PanelWorkOrder.setLayout(new java.awt.CardLayout());

        jLabel1.setBackground(new java.awt.Color(240, 240, 240));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        PanelWorkOrder.add(jLabel1, "card2");

        jPanel2.add(PanelWorkOrder);

        RightMenu.setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setLayout(new java.awt.GridLayout(0, 1));

        PanelWorkInProgress.setBackground(new java.awt.Color(255, 255, 255));
        PanelWorkInProgress.setLayout(new java.awt.CardLayout());

        workinprogress.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        workinprogress.setFont(new java.awt.Font("Tw Cen MT", 0, 24));
        PanelWorkInProgress.add(workinprogress, "card2");

        jPanel1.add(PanelWorkInProgress);

        PanelCard.setBackground(new java.awt.Color(153, 170, 181));
        PanelCard.setLayout(new java.awt.CardLayout());

        Cards.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        Cards.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelCard.add(Cards, "card2");

        jPanel1.add(PanelCard);

        RightMenu.add(jPanel1);

        jPanel3.setLayout(new java.awt.GridLayout(0, 1));

        PanelEmployee.setBackground(new java.awt.Color(153, 170, 181));
        PanelEmployee.setLayout(new java.awt.CardLayout());

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelEmployee.add(jLabel2, "card2");

        jPanel3.add(PanelEmployee);

        PanelExtra.setBackground(new java.awt.Color(255, 255, 255));
        PanelExtra.setLayout(new java.awt.CardLayout());

        Extra.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        Extra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Extra.setVerticalTextPosition(Extra.TOP);
        Extra.setHorizontalTextPosition(Extra.CENTER);
        PanelExtra.add(Extra, "card2");

        jPanel3.add(PanelExtra);

        RightMenu.add(jPanel3);

        jPanel2.add(RightMenu);


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 950, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    public void setUpHintText() {
    	if(MainRunner.hinttext.getHintText() == true) {           
            jLabel1.setText("Work Order");
            jLabel2.setText("Employee");
            workinprogress.setText("Work In Progress");
            Cards.setText("Cards");
            Extra.setText("Extra");

    	}else {
            jLabel1.setText("");
            jLabel2.setText("");
            workinprogress.setText("");
            Cards.setText("");
            Extra.setText("");
            
    	}
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cards;
    private javax.swing.JPanel PanelEmployee;
    private javax.swing.JLabel Extra;
    private javax.swing.JPanel RightMenu;
    private javax.swing.JPanel PanelWorkInProgress;
    private javax.swing.JPanel PanelWorkOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel PanelCard;
    private javax.swing.JPanel PanelExtra;
    private javax.swing.JLabel workinprogress;
    // End of variables declaration//GEN-END:variables
}
