/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui.WorkOrderGui;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Collections;

import javax.swing.ButtonGroup;
import javax.swing.JFrame;

import Runner.MainRunner;
import javax.swing.JMenu;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JPanel;
import java.awt.GridLayout;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;
import javax.swing.JButton;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author Mason Smith
 */
@SuppressWarnings("serial")
public class newWorkOrder extends javax.swing.JFrame {

	private LocalDateTime date;
	private DateTimeFormatter dateFormate;
	private File workOrderDirectory = new File("\\\\192.168.0.125\\ServiceMachineTimeCardSystem\\WorkOrders");
	private int lastWorkOrderNumber;
	private int part;

	/**
	 * Creates new form newWorkOrder
	 */
	public newWorkOrder(int part) {
		// sets up date stuff
		date = LocalDateTime.now();
		dateFormate = DateTimeFormatter.ofPattern("M/d/yyyy");
		//sets up part
		this.part = part;
		
		// sets up the last work order number
		getLastWorkOrderNumber();

		// sets up frame values
		initComponents();

	}

	public void getLastWorkOrderNumber() {
		// checks if work order directory is a valid directory
		if (workOrderDirectory.isDirectory()) {
			String[] fileList = workOrderDirectory.list();
			ArrayList<Integer> integerList = new ArrayList<Integer>();
			// adds file list strings to a integer array
			for (String list : fileList) {
				integerList.add(Integer.valueOf(list));
			}
			// sorts integers from lowest to highest 
			Collections.sort(integerList);
			// sets the value of last work order from the Integer List
			if(integerList.size() != 0) {
				lastWorkOrderNumber = integerList.get(integerList.size() -1);

			}else {
				lastWorkOrderNumber = 0;
			}
			//sets default values
			workOrderRun.mainWorkOrderNumber = String.valueOf(lastWorkOrderNumber + 1);
			workOrderRun.mainWorkOrderDate = dateFormate.toString();
		}
	}

	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel2.setName("Date/WorkOrderNumber");
        PanelDate = new javax.swing.JPanel();
        PanelDate.setName("Date");
        TextField_Date = new javax.swing.JFormattedTextField(dateFormate);
        TextField_Date.addFocusListener(new FocusAdapter() {
        	@Override
        	public void focusLost(FocusEvent arg0) {
        		workOrderRun.mainWorkOrderDate = TextField_Date.getText();
        		workOrderRun.upDateAllFrames();
        		checkValues();
        	}
        });
        TextField_Date.setName("TextField_Date");
        jLabel1 = new javax.swing.JLabel();
        PanelWorkOrderNumber = new javax.swing.JPanel();
        PanelWorkOrderNumber.setName("WorkOrderNumber");
        jLabel2 = new javax.swing.JLabel();
        TextField_WorkOrderNumber = new javax.swing.JFormattedTextField();
        TextField_WorkOrderNumber.addFocusListener(new FocusAdapter() {
        	@Override
        	public void focusLost(FocusEvent e) {
        		workOrderRun.mainWorkOrderNumber = TextField_WorkOrderNumber.getText();
        		workOrderRun.upDateAllFrames();
        		checkValues();
        	}
        });
        PanelCustomer = new javax.swing.JPanel();
        PanelCustomer.setName("Customer");
        jLabel3 = new javax.swing.JLabel();
        TextField_Customer = new javax.swing.JTextField();
        TextField_Customer.setFocusable(false);
        TextField_Customer.setName("TextField_Customer");
        TextField_Customer.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent arg0) {
        		JFrame selectCustomer = new customerSelect();
        		selectCustomer.setVisible(true);
        		selectCustomer.addWindowListener(new WindowAdapter() {
        			@Override
                    public void windowClosed(WindowEvent e)
                    {
        				if(workOrderRun.selectedCustomer != null) {
        					if(!workOrderRun.selectedCustomer.getName().equals("WalkIn")) {
        						TextField_Customer.setText(workOrderRun.workOrderSuper.getCustomer());
        					}else{
        						TextField_Customer.setText(workOrderRun.workOrderSuper.getCustomer().substring(8, workOrderRun.workOrderSuper.getCustomer().length()));
        					}
        					workOrderRun.upDateAllFrames();
        				}
        				checkValues();
                    }
        		});
        	}
        });
        jPanel4 = new javax.swing.JPanel();
        jPanel4.setName("Phone/Fax");
        PanelPhoneNumber = new javax.swing.JPanel();
        PanelPhoneNumber.setName("Phone");
        jLabel4 = new javax.swing.JLabel();
        TextField_Phone = new javax.swing.JTextField();
        TextField_Phone.addFocusListener(new FocusAdapter() {
        	@Override
        	public void focusLost(FocusEvent e) {
        		workOrderRun.mainWorkOrderPhone = TextField_Phone.getText();
        		workOrderRun.upDateAllFrames();
        		checkValues();
        	}
        });
        PanelFax = new javax.swing.JPanel();
        PanelFax.setName("Fax");
        jLabel5 = new javax.swing.JLabel();
        TextField_Fax = new javax.swing.JTextField();
        TextField_Fax.setHorizontalAlignment(SwingConstants.CENTER);
        TextField_Fax.addFocusListener(new FocusAdapter() {
        	@Override
        	public void focusLost(FocusEvent e) {
        		workOrderRun.mainWorkOrderFax = TextField_Fax.getText();
        		workOrderRun.upDateAllFrames();
        		checkValues();
        	}
        });
        jPanel5 = new javax.swing.JPanel();
        PanelOrderedBy = new javax.swing.JPanel();
        TextField_OrderedBy = new javax.swing.JTextField();
        TextField_OrderedBy.addFocusListener(new FocusAdapter() {
        	@Override
        	public void focusLost(FocusEvent e) {
        		checkValues();
        	}
        });
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        PanelDueDate = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        TextField_DueDate = new javax.swing.JFormattedTextField(dateFormate);
        TextField_DueDate.addFocusListener(new FocusAdapter() {
        	@Override
        	public void focusLost(FocusEvent e) {
        		checkValues();
        	}
        });
        jPanel3 = new javax.swing.JPanel();
        PanelRush = new javax.swing.JPanel();
        CheckBox_Rush = new javax.swing.JCheckBox();
        PanelOverTime = new javax.swing.JPanel();
        CheckBox_OverTime = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        PanelQty = new javax.swing.JPanel();
        TextField_Qty = new javax.swing.JTextField();
        TextField_Qty.addFocusListener(new FocusAdapter() {
        	@Override
        	public void focusLost(FocusEvent e) {
        		checkValues();
        	}
        });
        jLabel10 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        PanelShipVia = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        PanelSmc = new javax.swing.JPanel();
        CheckBox_SMC = new JRadioButton();
        jPanel15 = new javax.swing.JPanel();
        PanelMotorFreight = new javax.swing.JPanel();
        CheckBox_MotorFreight = new JRadioButton();
        PanelUps = new javax.swing.JPanel();
        CheckBox_Ups = new JRadioButton();
        jPanel16 = new javax.swing.JPanel();
        PanelCpu = new javax.swing.JPanel();
        CheckBox_Cpu = new JRadioButton();
        CheckBox_Cpu.setSelected(true);
        PanelCourier = new javax.swing.JPanel();
        CheckBox_Courier = new JRadioButton();
        PanelDescription = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jTextPane1.addFocusListener(new FocusAdapter() {
        	@Override
        	public void focusLost(FocusEvent e) {
        		checkValues();
        	}
        });
        PanelButtons = new javax.swing.JPanel();
        PanelSubmit = new javax.swing.JPanel();
        Button_Submit = new javax.swing.JButton();
        Button_Submit.setFont(new Font("Tw Cen MT Condensed", Font.PLAIN, 24));
        Button_Submit.setForeground(Color.RED);
        Button_Submit.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent arg0) {
        		//checks and saves values 
        		checkValues();
        		if(workOrderRun.currentPart == 0) {
        			//master save for checking all save values
        			Boolean masterSave = false;
            		//checks all work orders in the save list
    				for(int i = 0; i < workOrderRun.saveList.length; i++) {
    					if(workOrderRun.saveList[i].equals(false)) {
    						masterSave = false;
    						JOptionPane.showMessageDialog(newWorkOrder.this, "Missing Values at Part : " +  workOrderRun.alphabet[i]);
    						break;
    					}else {
    						masterSave = true;
    					}
    				}
    				
    				if(masterSave == true) {
    					workOrderRun.saveWorkOrder();
    					//closes frames and opens previous 
    	        		MainRunner.runWorkOrderMain();
    	        		workOrderRun.extraMenu.dispose();
    	        		newWorkOrder.this.dispose();
    				}else {
    					
    				}
        		}
        	}
        });
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu_Back = new javax.swing.JMenu();
        Menu_Back.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		//closes frames and opens previous 
        		MainRunner.runWorkOrderMain();
        		workOrderRun.extraMenu.dispose();
        		newWorkOrder.this.dispose();
        	}
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(720, 810));

        jPanel1.setMinimumSize(new java.awt.Dimension(720, 810));
        jPanel1.setPreferredSize(new java.awt.Dimension(720, 810));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setPreferredSize(new java.awt.Dimension(720, 50));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        PanelDate.setLayout(new java.awt.BorderLayout());

        TextField_Date.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextField_Date.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        TextField_Date.setPreferredSize(new java.awt.Dimension(360, 40));
        TextField_Date.setText(date.format(dateFormate));
        PanelDate.add(TextField_Date, java.awt.BorderLayout.PAGE_END);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel1.setText("Date");
        jLabel1.setMaximumSize(new java.awt.Dimension(20, 10));
        jLabel1.setMinimumSize(new java.awt.Dimension(43, 10));
        jLabel1.setPreferredSize(new java.awt.Dimension(360, 10));
        PanelDate.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel2.add(PanelDate);

        PanelWorkOrderNumber.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel2.setText("WorkOrder Number");
        jLabel2.setMinimumSize(new java.awt.Dimension(43, 10));
        jLabel2.setPreferredSize(new java.awt.Dimension(360, 10));
        PanelWorkOrderNumber.add(jLabel2, java.awt.BorderLayout.CENTER);

        TextField_WorkOrderNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextField_WorkOrderNumber.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        TextField_WorkOrderNumber.setPreferredSize(new java.awt.Dimension(360, 40));
        TextField_WorkOrderNumber.setText(String.valueOf(lastWorkOrderNumber + 1));
        PanelWorkOrderNumber.add(TextField_WorkOrderNumber, java.awt.BorderLayout.PAGE_END);

        jPanel2.add(PanelWorkOrderNumber);

        jPanel1.add(jPanel2);

        PanelCustomer.setPreferredSize(new java.awt.Dimension(720, 100));
        PanelCustomer.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel3.setText("Customer");
        jLabel3.setMinimumSize(new java.awt.Dimension(43, 10));
        jLabel3.setPreferredSize(new java.awt.Dimension(720, 10));
        PanelCustomer.add(jLabel3, java.awt.BorderLayout.CENTER);

        TextField_Customer.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        TextField_Customer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextField_Customer.setPreferredSize(new java.awt.Dimension(720, 90));
        PanelCustomer.add(TextField_Customer, java.awt.BorderLayout.PAGE_END);

        jPanel1.add(PanelCustomer);

        jPanel4.setPreferredSize(new java.awt.Dimension(720, 50));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        PanelPhoneNumber.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel4.setText("Phone");
        jLabel4.setMinimumSize(new java.awt.Dimension(43, 10));
        jLabel4.setPreferredSize(new java.awt.Dimension(360, 10));
        PanelPhoneNumber.add(jLabel4, java.awt.BorderLayout.CENTER);

        TextField_Phone.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        TextField_Phone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextField_Phone.setPreferredSize(new java.awt.Dimension(360, 40));
        PanelPhoneNumber.add(TextField_Phone, java.awt.BorderLayout.PAGE_END);

        jPanel4.add(PanelPhoneNumber);

        PanelFax.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel5.setText("Fax");
        jLabel5.setMinimumSize(new java.awt.Dimension(43, 10));
        jLabel5.setPreferredSize(new java.awt.Dimension(360, 10));
        PanelFax.add(jLabel5, java.awt.BorderLayout.CENTER);

        TextField_Fax.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        TextField_Fax.setPreferredSize(new java.awt.Dimension(360, 40));
        PanelFax.add(TextField_Fax, java.awt.BorderLayout.PAGE_END);

        jPanel4.add(PanelFax);

        jPanel1.add(jPanel4);

        jPanel5.setPreferredSize(new java.awt.Dimension(720, 50));
        jPanel5.setLayout(new GridLayout(0, 2, 0, 0));

        PanelOrderedBy.setPreferredSize(new Dimension(360, 50));
        PanelOrderedBy.setLayout(new java.awt.BorderLayout());

        TextField_OrderedBy.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        TextField_OrderedBy.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextField_OrderedBy.setPreferredSize(new Dimension(360, 40));
        PanelOrderedBy.add(TextField_OrderedBy, java.awt.BorderLayout.PAGE_END);

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel8.setText("Ordered By");
        jLabel8.setMinimumSize(new java.awt.Dimension(43, 10));
        jLabel8.setPreferredSize(new Dimension(360, 10));
        PanelOrderedBy.add(jLabel8, java.awt.BorderLayout.CENTER);

        jPanel5.add(PanelOrderedBy);

        jPanel1.add(jPanel5);

        jPanel6.setPreferredSize(new java.awt.Dimension(720, 50));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        PanelDueDate.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel7.setText("Due Date");
        jLabel7.setMinimumSize(new java.awt.Dimension(43, 10));
        jLabel7.setPreferredSize(new java.awt.Dimension(360, 10));
        PanelDueDate.add(jLabel7, java.awt.BorderLayout.CENTER);

        TextField_DueDate.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        TextField_DueDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextField_DueDate.setPreferredSize(new java.awt.Dimension(360, 40));
        LocalDateTime tempdate = date.plusDays(7);
        TextField_DueDate.setText(tempdate.format(dateFormate));
        PanelDueDate.add(TextField_DueDate, java.awt.BorderLayout.PAGE_END);

        jPanel6.add(PanelDueDate);

        jPanel3.setMinimumSize(new java.awt.Dimension(360, 50));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        PanelRush.setPreferredSize(new java.awt.Dimension(180, 50));
        PanelRush.setLayout(new java.awt.GridLayout(1, 0));

        CheckBox_Rush.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        CheckBox_Rush.setText("Rush");
        CheckBox_Rush.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CheckBox_Rush.setPreferredSize(new java.awt.Dimension(180, 50));
        PanelRush.add(CheckBox_Rush);

        jPanel3.add(PanelRush);

        PanelOverTime.setPreferredSize(new java.awt.Dimension(180, 50));
        PanelOverTime.setLayout(new java.awt.GridLayout(1, 0));

        CheckBox_OverTime.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        CheckBox_OverTime.setText("OverTime");
        CheckBox_OverTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CheckBox_OverTime.setPreferredSize(new java.awt.Dimension(180, 50));
        PanelOverTime.add(CheckBox_OverTime);

        jPanel3.add(PanelOverTime);

        jPanel6.add(jPanel3);

        jPanel1.add(jPanel6);

        jPanel7.setPreferredSize(new java.awt.Dimension(720, 50));
        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        PanelQty.setLayout(new java.awt.BorderLayout());

        TextField_Qty.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        TextField_Qty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextField_Qty.setPreferredSize(new java.awt.Dimension(360, 40));
        PanelQty.add(TextField_Qty, java.awt.BorderLayout.PAGE_END);

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel10.setText("Qty");
        jLabel10.setToolTipText("");
        jLabel10.setMinimumSize(new java.awt.Dimension(43, 10));
        jLabel10.setPreferredSize(new java.awt.Dimension(360, 10));
        PanelQty.add(jLabel10, java.awt.BorderLayout.CENTER);

        jPanel7.add(PanelQty);

        jPanel13.setLayout(new java.awt.GridLayout(0, 3));

        jPanel14.setLayout(new java.awt.GridLayout(0, 1));

        PanelShipVia.setLayout(new java.awt.BorderLayout());

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel9.setText("Ship Via:");
        PanelShipVia.add(jLabel9, java.awt.BorderLayout.CENTER);

        jPanel14.add(PanelShipVia);

        PanelSmc.setLayout(new java.awt.BorderLayout());

        CheckBox_SMC.setText("SMC");
        PanelSmc.add(CheckBox_SMC, java.awt.BorderLayout.CENTER);

        jPanel14.add(PanelSmc);

        jPanel13.add(jPanel14);

        jPanel15.setLayout(new java.awt.GridLayout(0, 1));

        PanelMotorFreight.setLayout(new java.awt.BorderLayout());

        CheckBox_MotorFreight.setText("Motor Freight");
        PanelMotorFreight.add(CheckBox_MotorFreight, java.awt.BorderLayout.CENTER);

        jPanel15.add(PanelMotorFreight);

        PanelUps.setLayout(new java.awt.BorderLayout());

        CheckBox_Ups.setText("UPS");
        PanelUps.add(CheckBox_Ups, java.awt.BorderLayout.CENTER);

        jPanel15.add(PanelUps);

        jPanel13.add(jPanel15);

        jPanel16.setLayout(new java.awt.GridLayout(0, 1));

        PanelCpu.setLayout(new java.awt.BorderLayout());

        CheckBox_Cpu.setText("CPU");
        PanelCpu.add(CheckBox_Cpu, java.awt.BorderLayout.CENTER);

        jPanel16.add(PanelCpu);

        PanelCourier.setLayout(new java.awt.BorderLayout());

        CheckBox_Courier.setText("Courier");
        CheckBox_Courier.setToolTipText("");
        PanelCourier.add(CheckBox_Courier, java.awt.BorderLayout.CENTER);

        jPanel16.add(PanelCourier);

        jPanel13.add(jPanel16);

        jPanel7.add(jPanel13);

        jPanel1.add(jPanel7);

        PanelDescription.setPreferredSize(new java.awt.Dimension(720, 375));
        PanelDescription.setLayout(new java.awt.BorderLayout());

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel11.setText("Description");
        jLabel11.setToolTipText("");
        jLabel11.setMinimumSize(new java.awt.Dimension(43, 10));
        jLabel11.setPreferredSize(new java.awt.Dimension(720, 10));
        PanelDescription.add(jLabel11, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextPane1.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        PanelDescription.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(PanelDescription);

        PanelButtons.setPreferredSize(new Dimension(720, 100));
        PanelButtons.setLayout(new GridLayout(0, 1, 0, 0));

        PanelSubmit.setPreferredSize(new java.awt.Dimension(360, 100));
        PanelSubmit.setLayout(new java.awt.BorderLayout());

        Button_Submit.setText("Save");
        PanelSubmit.add(Button_Submit, java.awt.BorderLayout.CENTER);

        PanelButtons.add(PanelSubmit);

        jPanel1.add(PanelButtons);
        
        //checks if arrows are needed
        if(workOrderRun.workOrderSuper.multiPart == true) {
        	//adds arrow options to bottom of frame
        	PanelArrowMenu = new JPanel();
            PanelButtons.add(PanelArrowMenu);
            PanelArrowMenu.setLayout(new GridLayout(1, 0, 0, 0));
            
            Button_LeftArrow = new JButton("");
            Button_LeftArrow.setIcon(new ImageIcon(newWorkOrder.class.getResource("/Resources/left-arrow-icon.png")));
            PanelArrowMenu.add(Button_LeftArrow);
            
            Button_RightArrow = new JButton("");
            Button_RightArrow.setIcon(new ImageIcon(newWorkOrder.class.getResource("/Resources/right-arrow-icon.png")));
            PanelArrowMenu.add(Button_RightArrow);
            
            Button_RightArrow.addMouseListener(new MouseAdapter() {
            	@Override
            	public void mouseClicked(MouseEvent arg0) {
            		checkValues();
            		if(workOrderRun.currentPart == 0) {
            			//sets all variables and updates text for all frames
            			workOrderRun.mainWorkOrderDate = TextField_Date.getText();
                		workOrderRun.mainWorkOrderNumber = TextField_WorkOrderNumber.getText();
                		workOrderRun.mainWorkOrderPhone = TextField_Phone.getText();
                		workOrderRun.mainWorkOrderFax = TextField_Fax.getText();
                		workOrderRun.upDateAllFrames();


            		}
            		workOrderRun.nextWorkOrder();
            	}
            });
            
            Button_LeftArrow.addMouseListener(new MouseAdapter() {
            	@Override
            	public void mouseClicked(MouseEvent arg0) {
            		checkValues();
            		workOrderRun.previousWorkOrder();
            	}
            });
            
        }else {
        	//changes frame dimension so it fits in the frame
        	PanelButtons.setPreferredSize(new Dimension(720, 50));
        }

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenuBar1.setPreferredSize(new java.awt.Dimension(50, 21));

        Menu_Back.setText("Back");
        jMenuBar1.add(Menu_Back);

        setJMenuBar(jMenuBar1);
        
        mnExtraMenu = new JMenu("Extra Menu");
        mnExtraMenu.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		workOrderRun.extraMenu.setVisible(true);
        	}
        });
        jMenuBar1.add(mnExtraMenu);
        
        ButtonGroup shipViaButtonGroup = new ButtonGroup();
        shipViaButtonGroup.add(CheckBox_SMC);
        shipViaButtonGroup.add(CheckBox_MotorFreight);
        shipViaButtonGroup.add(CheckBox_Ups);
        shipViaButtonGroup.add(CheckBox_Cpu);
        shipViaButtonGroup.add(CheckBox_Courier);
        
        ButtonGroup chargeButtonGroup = new ButtonGroup();
        
        panel = new JPanel();
        jPanel5.add(panel);
        panel.setLayout(new GridLayout(0, 2, 0, 0));
        PanelCharge = new javax.swing.JPanel();
        panel.add(PanelCharge);
        PanelCharge.setPreferredSize(new Dimension(180, 50));
        CheckBox_Charge = new JRadioButton();
        PanelCharge.setLayout(new java.awt.BorderLayout());
                
        CheckBox_Charge.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        CheckBox_Charge.setText("Charge");
        CheckBox_Charge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelCharge.add(CheckBox_Charge, java.awt.BorderLayout.CENTER);
        chargeButtonGroup.add(CheckBox_Charge);
        PanelCOD = new javax.swing.JPanel();
        panel.add(PanelCOD);
        CheckBox_COD = new JRadioButton();
        CheckBox_COD.setPreferredSize(new Dimension(180, 50));
        CheckBox_COD.setSelected(true);
                        
        PanelCOD.setLayout(new java.awt.BorderLayout());
                                
        CheckBox_COD.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        CheckBox_COD.setText("COD");
        CheckBox_COD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelCOD.add(CheckBox_COD, java.awt.BorderLayout.CENTER);
        chargeButtonGroup.add(CheckBox_COD);
        
        //checks if the current part is not the fist
        //if that is the case some parts of the work order form are disabled so the work orders do not get confused
        if(this.part != 0) {
        	//removes the customer select function
        	for( MouseListener al : TextField_Customer.getMouseListeners() ) {
        		TextField_Customer.removeMouseListener(al);
        	}
        	//removes the work order number change function
        	TextField_WorkOrderNumber.setFocusable(false);
        	//removes the change phone number function
        	TextField_Phone.setFocusable(false);
        	//removes the change fax number function 
        	TextField_Fax.setFocusable(false);
        	
        	
        }
        
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //checks if all values that are need meet condition
    public boolean checkValues() {
    	//set boolean to false if any required text field has no value
		Boolean hasValues = true;
		//used to save workOrder
		if(TextField_Date.getText().trim().length() <= 0) {
			hasValues = false;
			
		}else if(TextField_WorkOrderNumber.getText().trim().length() <= 0) {
			hasValues = false;
			
		}else if(workOrderRun.workOrderSuper.getCustomer() == null) {
			hasValues = false;
			
		}else if(TextField_Phone.getText().trim().length() <= 0) {
			hasValues = false;
			
		}else if(TextField_OrderedBy.getText().trim().length() <= 0) {
			hasValues = false;
			
		}else if(TextField_DueDate.getText().trim().length() <= 0) {
			hasValues = false;
			
		}else if(TextField_Qty.getText().trim().length() <= 0) {
			hasValues = false;
			
		}else if(jTextPane1.getText().trim().length() <= 0) {
			hasValues = false;
			
		}
		//checks if the text field qty has a value and is a allowable integer
		if(TextField_Qty.getText().trim().length() > 0) {
			try {
				Integer.parseInt(TextField_Qty.getText());
			}catch(NumberFormatException exception) {
				JOptionPane.showMessageDialog(newWorkOrder.this, "Qty must be a number");
				hasValues = false;
			}
		}
		
		
		//runs after all required text fields are checked for any value 
		if(hasValues == true) {
			workOrderRun.workOrderSuper.setWorkOrderNumber(TextField_WorkOrderNumber.getText());
			//if all require values are valid
			saveValues();
			Button_Submit.setForeground(Color.GREEN);
			workOrderRun.saveList[workOrderRun.currentPart] = true;			
			return true;
		}else {
			//if all required values are invalid
			Button_Submit.setForeground(Color.RED);
			workOrderRun.saveList[workOrderRun.currentPart] = false;
			return false;
		}
		
		
    }
        
    public void saveValues() {
    	//if work order is not primary
    	workOrderRun.workOrderSuper.workOrderList.get(workOrderRun.currentPart).setDate(TextField_Date.getText());
    	workOrderRun.workOrderSuper.workOrderList.get(workOrderRun.currentPart).setPhone(TextField_Phone.getText());
    	workOrderRun.workOrderSuper.workOrderList.get(workOrderRun.currentPart).setFax(TextField_Fax.getText());
    	workOrderRun.workOrderSuper.workOrderList.get(workOrderRun.currentPart).setOrderedBy(TextField_OrderedBy.getText());
    	workOrderRun.workOrderSuper.workOrderList.get(workOrderRun.currentPart).setDueDate(TextField_DueDate.getText());
    	workOrderRun.workOrderSuper.workOrderList.get(workOrderRun.currentPart).setQty(Integer.parseInt(TextField_Qty.getText()));
    	workOrderRun.workOrderSuper.workOrderList.get(workOrderRun.currentPart).setRush(CheckBox_Rush.isSelected());
    	workOrderRun.workOrderSuper.workOrderList.get(workOrderRun.currentPart).setOverTime(CheckBox_OverTime.isSelected());
    	workOrderRun.workOrderSuper.workOrderList.get(workOrderRun.currentPart).setDescription(jTextPane1.getText());
    		
    	//handles button groups ship via
    		workOrderRun.workOrderSuper.workOrderList.get(workOrderRun.currentPart).setCourier(CheckBox_Courier.isSelected());
    		workOrderRun.workOrderSuper.workOrderList.get(workOrderRun.currentPart).setCpu(CheckBox_Cpu.isSelected());
    		workOrderRun.workOrderSuper.workOrderList.get(workOrderRun.currentPart).setMotorFreight(CheckBox_MotorFreight.isSelected());
    		workOrderRun.workOrderSuper.workOrderList.get(workOrderRun.currentPart).setSmc(CheckBox_SMC.isSelected());
    		workOrderRun.workOrderSuper.workOrderList.get(workOrderRun.currentPart).setSmc(CheckBox_Ups.isSelected());
    	//handles charge/cod button group
    		workOrderRun.workOrderSuper.workOrderList.get(workOrderRun.currentPart).setCod(CheckBox_COD.isSelected());
    		workOrderRun.workOrderSuper.workOrderList.get(workOrderRun.currentPart).setCharge(CheckBox_Charge.isSelected());
    }
    
    
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton Button_Submit;
	private JRadioButton CheckBox_COD;
	private JRadioButton CheckBox_Charge;
	private JRadioButton CheckBox_Courier;
	private JRadioButton CheckBox_Cpu;
	private JRadioButton CheckBox_MotorFreight;
	private javax.swing.JCheckBox CheckBox_OverTime;
	private javax.swing.JCheckBox CheckBox_Rush;
	private JRadioButton CheckBox_SMC;
	private JRadioButton CheckBox_Ups;
	private javax.swing.JMenu Menu_Back;
	private javax.swing.JPanel PanelButtons;
	private javax.swing.JPanel PanelCOD;
	private javax.swing.JPanel PanelCharge;
	private javax.swing.JPanel PanelCourier;
	private javax.swing.JPanel PanelCpu;
	private javax.swing.JPanel PanelCustomer;
	private javax.swing.JPanel PanelDate;
	private javax.swing.JPanel PanelDescription;
	private javax.swing.JPanel PanelDueDate;
	private javax.swing.JPanel PanelFax;
	private javax.swing.JPanel PanelMotorFreight;
	private javax.swing.JPanel PanelOrderedBy;
	private javax.swing.JPanel PanelOverTime;
	private javax.swing.JPanel PanelPhoneNumber;
	private javax.swing.JPanel PanelQty;
	private javax.swing.JPanel PanelRush;
	private javax.swing.JPanel PanelShipVia;
	private javax.swing.JPanel PanelSmc;
	private javax.swing.JPanel PanelSubmit;
	private javax.swing.JPanel PanelUps;
	private javax.swing.JPanel PanelWorkOrderNumber;
	private javax.swing.JTextField TextField_Customer;
	private javax.swing.JFormattedTextField TextField_Date;
	private javax.swing.JTextField TextField_DueDate;
	private javax.swing.JTextField TextField_Fax;
	private javax.swing.JTextField TextField_OrderedBy;
	private javax.swing.JTextField TextField_Phone;
	private javax.swing.JTextField TextField_Qty;
	private javax.swing.JFormattedTextField TextField_WorkOrderNumber;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel13;
	private javax.swing.JPanel jPanel14;
	private javax.swing.JPanel jPanel15;
	private javax.swing.JPanel jPanel16;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextPane jTextPane1;
	private JMenu mnExtraMenu;
	private JPanel PanelArrowMenu;
	private JButton Button_LeftArrow;
	private JButton Button_RightArrow;
	private JPanel panel;
	// End of variables declaration//GEN-END:variables
}
