/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui.WorkOrderGui;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.JPanel;
import java.awt.GridLayout;
import javax.swing.JCheckBox;
import javax.swing.SwingConstants;
import java.awt.Font;
import java.awt.event.ItemListener;
import java.awt.event.ItemEvent;
import java.awt.Dimension;

/**
 *
 * @author Mason Smith
 */
@SuppressWarnings("serial")
public class workOrderExtraMenu extends javax.swing.JFrame {
	
	String title = "";
	
    /**
     * Creates new form workOrderExtraMenu
     */
    public workOrderExtraMenu() {
    	setTitle("workOrderExtra");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ButtonMatterial = new javax.swing.JButton();
        ButtonMatterial.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent arg0) {
        		
        		MatterialMenu matterialMenu = new MatterialMenu(workOrderRun.currentPart);
        		matterialMenu.setVisible(true); 
        	}
        });
        jPanel3 = new javax.swing.JPanel();
        ButtonPoNumber = new javax.swing.JButton();
        ButtonPoNumber.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		
        	}
        });
        jPanel4 = new javax.swing.JPanel();
        ButtonDeliveryTicket = new javax.swing.JButton();
        ButtonDeliveryTicket.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		
        	}
        });
        jPanel5 = new javax.swing.JPanel();
        ButtonInvoiceNumber = new javax.swing.JButton();
        ButtonInvoiceNumber.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		
        	}
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("workOrderExtra");
        setMinimumSize(new java.awt.Dimension(200, 350));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setMinimumSize(new Dimension(200, 400));
        jPanel1.setLayout(new GridLayout(0, 1, 0, 0));

        jPanel2.setPreferredSize(new java.awt.Dimension(200, 87));
        jPanel2.setLayout(new java.awt.BorderLayout());

        ButtonMatterial.setBackground(new java.awt.Color(255, 255, 255));
        ButtonMatterial.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        ButtonMatterial.setText("Matterial");
        jPanel2.add(ButtonMatterial, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2);

        jPanel3.setPreferredSize(new java.awt.Dimension(200, 87));
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.setLayout(new java.awt.BorderLayout());

        ButtonPoNumber.setBackground(new java.awt.Color(153, 170, 181));
        ButtonPoNumber.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        ButtonPoNumber.setText("PO Number");
        jPanel3.add(ButtonPoNumber, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3);

        jPanel4.setPreferredSize(new java.awt.Dimension(200, 87));
        jPanel4.setLayout(new java.awt.BorderLayout());

        ButtonDeliveryTicket.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        ButtonDeliveryTicket.setText("Delivery Ticket");
        ButtonDeliveryTicket.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.add(ButtonDeliveryTicket, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4);

        jPanel5.setPreferredSize(new java.awt.Dimension(200, 87));
        jPanel5.setLayout(new java.awt.BorderLayout());

        ButtonInvoiceNumber.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        ButtonInvoiceNumber.setBackground(new java.awt.Color(153, 170, 181));
        ButtonInvoiceNumber.setText("Invoice Number");
        jPanel5.add(ButtonInvoiceNumber, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel5);

        getContentPane().add(jPanel1);
        
        panel = new JPanel();
        jPanel1.add(panel);
        panel.setLayout(new GridLayout(0, 1, 0, 0));
        
        chckbxCashJob = new JCheckBox("CASH JOB");
        chckbxCashJob.addItemListener(new ItemListener() {
        	public void itemStateChanged(ItemEvent e) {
        		if(e.getStateChange() == ItemEvent.SELECTED) {
        			workOrderRun.workOrderSuper.setCashJob(true);
        		}else if(e.getStateChange() == ItemEvent.DESELECTED) {
        			workOrderRun.workOrderSuper.setCashJob(false);
        		}        		
        	}
        });
        chckbxCashJob.setFont(new Font("Tw Cen MT Condensed", Font.PLAIN, 36));
        chckbxCashJob.setHorizontalAlignment(SwingConstants.CENTER);
        panel.add(chckbxCashJob);
        
        panel_1 = new JPanel();
        jPanel1.add(panel_1);
        panel_1.setLayout(new GridLayout(0, 1, 0, 0));
        
        chckbxWorkInProgress = new JCheckBox("In Progress");
        chckbxWorkInProgress.setSelected(true);
        chckbxWorkInProgress.addItemListener(new ItemListener() {
        	public void itemStateChanged(ItemEvent e) {
        		if(e.getStateChange() == ItemEvent.SELECTED) {
        			workOrderRun.workOrderSuper.setInProgress(true);
        		}else if(e.getStateChange() == ItemEvent.DESELECTED) {
        			workOrderRun.workOrderSuper.setInProgress(false);
        		}        		
        	}
        });
        chckbxWorkInProgress.setHorizontalAlignment(SwingConstants.CENTER);
        chckbxWorkInProgress.setFont(new Font("Tw Cen MT Condensed", Font.PLAIN, 36));
        panel_1.add(chckbxWorkInProgress);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonMatterial;
    private javax.swing.JButton ButtonPoNumber;
    private javax.swing.JButton ButtonDeliveryTicket;
    private javax.swing.JButton ButtonInvoiceNumber;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private JPanel panel;
    private JCheckBox chckbxCashJob;
    private JPanel panel_1;
    private JCheckBox chckbxWorkInProgress;
    // End of variables declaration//GEN-END:variables
}
