/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui.ExtraGui;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

import Custom.FileHandler;
import Objects.Machine;
import Runner.MainRunner;

import java.awt.Frame;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.GridLayout;
import javax.swing.JCheckBox;
import javax.swing.SwingConstants;
import java.awt.Font;

/**
 *
 * @author Mason Smith
 */
@SuppressWarnings("serial")
public class editMachine extends javax.swing.JFrame {

	public File machinePicture = new File("");
	public BufferedImage resizedImage = null;
	public Machine selectedMachine = null;

	
    /**
     * Creates new form newMachine
     */
    public editMachine(Machine machine) {
    	this.selectedMachine = machine;
    	setTitle("editMachine");
        initComponents();
        setUpText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
    	//sets the location of frame to middle of screen
    	GraphicsDevice gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
    	this.setLocation(gd.getDisplayMode().getWidth()/4-this.getSize().width/2, gd.getDisplayMode().getHeight()/4-this.getSize().height/2);

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        LabelProfilePicture = new javax.swing.JLabel();
        LabelProfilePicture.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		//when profile picture is clicked
        		JFileChooser chooser = new JFileChooser();
                FileNameExtensionFilter filter = new FileNameExtensionFilter(
                        "JPG & GIF Images", "jpg", "gif", "png");
                chooser.setFileFilter(filter);
                int returnVal = chooser.showOpenDialog(null);
                if(returnVal == JFileChooser.APPROVE_OPTION) {
                	try {
                		//gets selected image and resizes it to 150,150
                		FileHandler fileHandler = new FileHandler();
                		machinePicture = chooser.getSelectedFile();
						Image image = ImageIO.read(chooser.getSelectedFile());
						resizedImage = fileHandler.resizeImage(image, 150, 150);
						LabelProfilePicture.setIcon(new ImageIcon(resizedImage)); // NOI18N						
					} catch (IOException g) {
						// TODO Auto-generated catch block
						JOptionPane.showMessageDialog(getParent(), g.getMessage());
					}      
                }
        	}
        });
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        TextField_MachineType = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        TextField_MachineName = new javax.swing.JTextField();
        TextField_MachineName.addFocusListener(new FocusAdapter() {
        	@Override
        	public void focusGained(FocusEvent arg0) {
        		TextField_MachineCode.requestFocus();
        		JOptionPane.showMessageDialog(getParent(), "Machine Name Can Not Be Changed");     	
        	}
        });
        jPanel6 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        TextField_MachineCode = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        TextField_MachineCost = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        TextField_MachineBrand = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        TextField_MachineSerialNumber = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        Btn_Submit = new javax.swing.JButton();
        Btn_Submit.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		//sets up the value
        		Double cost = null;
        		
        		//check if cost is a valid double
    			try {
    				cost = Double.valueOf(TextField_MachineCost.getText());
    			}catch(NumberFormatException numberException) {
    				JOptionPane.showMessageDialog(getParent(), TextField_MachineCost.getText() + " : is not a valid cost");
    			}
    			if(cost != null) {
    				if(TextField_MachineCode.getText().equals("")) {
    					JOptionPane.showMessageDialog(getParent(), "Machine Code Required");
    				}else if(TextField_MachineName.getText().equals("")) {
    					JOptionPane.showMessageDialog(getParent(), "Machine Name Required");
    				}else if(TextField_MachineType.getText().equals("")) {
    					JOptionPane.showMessageDialog(getParent(), "Machine Type Required");
    				}else {
    					Machine saveMachine = new Machine();
            			saveMachine.setBrand(TextField_MachineBrand.getText());
            			saveMachine.setCode(TextField_MachineCode.getText());
            			saveMachine.setCost(cost);
            			saveMachine.setName(TextField_MachineName.getText());
            			saveMachine.setSerialNumber(TextField_MachineSerialNumber.getText());
            			saveMachine.setType(TextField_MachineType.getText());
            			saveMachine.setActive(chckbxEnable.isSelected());
            			
            			FileHandler fileHandler = new FileHandler();
            			new File("\\\\192.168.0.125\\ServiceMachineTimeCardSystem\\Machines" + "\\" + TextField_MachineCode.getText()).mkdir();
            			fileHandler.writeFile(new File("\\\\192.168.0.125\\ServiceMachineTimeCardSystem\\Machines" + "\\" + TextField_MachineCode.getText() + "\\" + TextField_MachineCode.getText() + ".JSON"), saveMachine);
            			
            			//checks if an image of the machine is present
                		if(resizedImage != null) {
                			File dest = new File("\\\\192.168.0.125\\ServiceMachineTimeCardSystem\\Machines" + "\\" + TextField_MachineCode.getText() + "\\" + "MachinePicture " +TextField_MachineCode.getText() + ".jpg");
                			try {
        						ImageIO.write(resizedImage, "jpg", dest);
        					} catch (IOException e1) {
        						// TODO Auto-generated catch block
        	    				JOptionPane.showMessageDialog(getParent(), "Machine Image Failed To Write Please Retry");
        					}
                		}
                		MainRunner.runExtraMain();
                		
                		//finds current frame out of listed frames and disposes of it
                		for(int i = 0; i < Frame.getFrames().length; i++) {
                			if(Frame.getFrames()[i].getTitle().equals("editMachine")) {
                				Frame.getFrames()[i].dispose();
                			}
                		}
                		
    				}    				
    			}       		
        	}
        });
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu_Back = new javax.swing.JMenu();
        Menu_Back.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent arg0) {
        		MainRunner.runEditMachine();
        		
        		//finds current frame out of listed frames and disposes of it
        		for(int i = 0; i < Frame.getFrames().length; i++) {
        			if(Frame.getFrames()[i].getTitle().equals("editMachine")) {
        				Frame.getFrames()[i].dispose();
        			}
        		}
        	}
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setPreferredSize(new java.awt.Dimension(200, 400));
        GridLayout gl_jPanel2 = new GridLayout();
        gl_jPanel2.setColumns(1);
        gl_jPanel2.setRows(0);
        jPanel2.setLayout(gl_jPanel2);

        LabelProfilePicture.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        LabelProfilePicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelProfilePicture.setIcon(new ImageIcon(editMachine.class.getResource("/Resources/user-picture.png"))); // NOI18N
        LabelProfilePicture.setText("Machine Image");
        LabelProfilePicture.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LabelProfilePicture.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(LabelProfilePicture);

        jPanel1.add(jPanel2);
        
        chckbxEnable = new JCheckBox("Enable");
        chckbxEnable.setFont(new Font("Tw Cen MT Condensed", Font.PLAIN, 24));
        chckbxEnable.setHorizontalAlignment(SwingConstants.CENTER);
        jPanel2.add(chckbxEnable);

        jPanel3.setPreferredSize(new java.awt.Dimension(600, 400));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jPanel11.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel11.setLayout(new java.awt.GridLayout());

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Machine Type:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel11.add(jLabel2);
        jPanel4.add(jPanel11);

        jPanel12.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel12.setLayout(new java.awt.GridLayout());

        TextField_MachineType.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        TextField_MachineType.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextField_MachineType.setMinimumSize(new java.awt.Dimension(500, 50));
        TextField_MachineType.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel12.add(TextField_MachineType);

        jPanel4.add(jPanel12);

        jPanel3.add(jPanel4);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jPanel13.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel13.setLayout(new java.awt.GridLayout());

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Machine Name:");
        jPanel13.add(jLabel3);

        jPanel5.add(jPanel13);

        jPanel14.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel14.setLayout(new java.awt.GridLayout());

        TextField_MachineName.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        TextField_MachineName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextField_MachineName.setMinimumSize(new java.awt.Dimension(500, 50));
        TextField_MachineName.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel14.add(TextField_MachineName);

        jPanel5.add(jPanel14);

        jPanel3.add(jPanel5);

        jPanel6.setMinimumSize(new java.awt.Dimension(600, 50));
        jPanel6.setPreferredSize(new java.awt.Dimension(600, 50));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jPanel17.setMinimumSize(new java.awt.Dimension(100, 50));
        jPanel17.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel17.setLayout(new java.awt.GridLayout());

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Machine Code:");
        jPanel17.add(jLabel5);

        jPanel6.add(jPanel17);

        jPanel18.setMinimumSize(new java.awt.Dimension(500, 50));
        jPanel18.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel18.setLayout(new java.awt.GridLayout());

        TextField_MachineCode.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        TextField_MachineCode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel18.add(TextField_MachineCode);

        jPanel6.add(jPanel18);

        jPanel3.add(jPanel6);

        jPanel7.setPreferredSize(new java.awt.Dimension(600, 50));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jPanel15.setMinimumSize(new java.awt.Dimension(100, 50));
        jPanel15.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel15.setLayout(new java.awt.GridLayout());

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Machine Cost:");
        jPanel15.add(jLabel4);

        jPanel7.add(jPanel15);

        jPanel16.setMinimumSize(new java.awt.Dimension(500, 50));
        jPanel16.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel16.setLayout(new java.awt.GridLayout());

        TextField_MachineCost.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        TextField_MachineCost.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel16.add(TextField_MachineCost);

        jPanel7.add(jPanel16);

        jPanel3.add(jPanel7);

        jPanel8.setPreferredSize(new java.awt.Dimension(600, 50));
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));

        jPanel19.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel19.setLayout(new java.awt.GridLayout());

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Machine Brand:");
        jPanel19.add(jLabel6);

        jPanel8.add(jPanel19);

        jPanel20.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel20.setLayout(new java.awt.GridLayout());

        TextField_MachineBrand.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        TextField_MachineBrand.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel20.add(TextField_MachineBrand);

        jPanel8.add(jPanel20);

        jPanel3.add(jPanel8);

        jPanel9.setPreferredSize(new java.awt.Dimension(600, 50));
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.LINE_AXIS));

        jPanel21.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel21.setLayout(new java.awt.GridLayout());

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Machine Serial:");
        jPanel21.add(jLabel7);

        jPanel9.add(jPanel21);

        jPanel22.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel22.setLayout(new java.awt.GridLayout());

        TextField_MachineSerialNumber.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        TextField_MachineSerialNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel22.add(TextField_MachineSerialNumber);

        jPanel9.add(jPanel22);

        jPanel3.add(jPanel9);

        jPanel10.setPreferredSize(new java.awt.Dimension(600, 100));
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.LINE_AXIS));

        jPanel23.setLayout(new java.awt.GridLayout(1, 0, 50, 50));

        Btn_Submit.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 48)); // NOI18N
        Btn_Submit.setText("Save");
        Btn_Submit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel23.add(Btn_Submit);

        jPanel10.add(jPanel23);

        jPanel3.add(jPanel10);

        jPanel1.add(jPanel3);

        getContentPane().add(jPanel1);

        jMenuBar1.setPreferredSize(new java.awt.Dimension(56, 20));

        Menu_Back.setText("Back");
        jMenuBar1.add(Menu_Back);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setUpText() {
    	TextField_MachineType.setText(selectedMachine.getType());
    	TextField_MachineName.setText(selectedMachine.getName());
    	TextField_MachineCode.setText(selectedMachine.getCode());
    	if(selectedMachine.getCost() != null) {
    		TextField_MachineCost.setText(selectedMachine.getCost().toString());
    	}
    	TextField_MachineBrand.setText(selectedMachine.getBrand());
    	TextField_MachineSerialNumber.setText(selectedMachine.getSerialNumber());
		File selectedMachineImage = new File("\\\\192.168.0.125\\ServiceMachineTimeCardSystem\\Machines" + "\\" + selectedMachine.getCode() + "\\" + "MachinePicture " + selectedMachine.getCode() + ".jpg");
		if(selectedMachineImage.exists()) {
			LabelProfilePicture.setIcon(new ImageIcon(selectedMachineImage.getPath()));
		}
		chckbxEnable.setSelected(selectedMachine.active);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Submit;
    private javax.swing.JLabel LabelProfilePicture;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu Menu_Back;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField TextField_MachineType;
    private javax.swing.JTextField TextField_MachineName;
    private javax.swing.JTextField TextField_MachineCode;
    private javax.swing.JTextField TextField_MachineCost;
    private javax.swing.JTextField TextField_MachineBrand;
    private javax.swing.JTextField TextField_MachineSerialNumber;
    private JCheckBox chckbxEnable;
    // End of variables declaration//GEN-END:variables
}
