/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui.EmployeeGui;
import java.io.File;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ScrollPaneConstants;

import Custom.FileHandler;
import Objects.Employee;
import Runner.MainRunner;

import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author Mason Smith
 */
@SuppressWarnings("serial")
public class findEmployee extends javax.swing.JFrame {

	public File employeeDirectory = new File("\\\\192.168.0.125\\ServiceMachineTimeCardSystem\\Employees\\");
	
	public String[] employeeList = employeeDirectory.list();
	
	public Employee employee = null;
    /**
     * Creates new form findEmployee
     */
    public findEmployee() {
    	setTitle("findEmployee");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	//sets the location of frame to middle of screen
    	GraphicsDevice gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
    	this.setLocation(gd.getDisplayMode().getWidth()/4-this.getSize().width/2, gd.getDisplayMode().getHeight()/4-this.getSize().height/2);
    	
        PanelPreview = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Label_ProfilePicture = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Label_Name = new javax.swing.JLabel();
        PanelSelect = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        ScrollPane_Employees = new javax.swing.JScrollPane();
        ScrollPane_Employees.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        List_Employees = new javax.swing.JList<>();
        List_Employees.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		//gets the selected directory for employee
        		File selectedEmployeeDirectory = new File(employeeDirectory.getAbsolutePath() + "\\" + List_Employees.getSelectedValue());
        		
        		//gets the selected file for object location
        		File selectedEmployeeFile = new File(selectedEmployeeDirectory.getAbsolutePath() + "\\" + List_Employees.getSelectedValue() + ".json");
        		
        		//gets the employee object
        		FileHandler fileHandler = new FileHandler();
    			employee = fileHandler.getEmployee(selectedEmployeeFile);
    			
    			//sets preview name
    			Label_Name.setText(employee.getName());
        		
    			//checks if there is a picture then sets it in the preview
    			if(employee.pictureLocaitonPath != null) {
    				Label_ProfilePicture.setIcon(new ImageIcon(employee.getPictureLocaitonPath()));
    			}else {
    				Label_ProfilePicture.setIcon(new ImageIcon(findEmployee.class.getResource("/Resources/user-picture.png"))); // NOI18N
    			}
        	}
        });
        jPanel2 = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();
        btnEdit.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent arg0) {
        		if(employee == null) {
        			JOptionPane.showMessageDialog(getParent(), "You Must select an employee");
        		}else {
        			MainRunner.runEmployeeEdit(employee);
        			findEmployee.this.dispose();
        		}
        	}
        });
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuBack = new javax.swing.JMenu();
        MenuBack.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent arg0) {
        		MainRunner.runEmployeeMain();
        		findEmployee.this.dispose();
        	}
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(960, 560));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        PanelPreview.setMinimumSize(new java.awt.Dimension(320, 540));
        PanelPreview.setPreferredSize(new java.awt.Dimension(320, 540));
        PanelPreview.setLayout(new javax.swing.BoxLayout(PanelPreview, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel3.setBackground(new java.awt.Color(114, 137, 218));
        jPanel3.setMinimumSize(new java.awt.Dimension(320, 270));
        jPanel3.setPreferredSize(new java.awt.Dimension(320, 270));
        jPanel3.setLayout(new java.awt.GridLayout());

        Label_ProfilePicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_ProfilePicture.setIcon(new ImageIcon(findEmployee.class.getResource("/Resources/user-picture.png"))); // NOI18N
        Label_ProfilePicture.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(Label_ProfilePicture);

        PanelPreview.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(114, 137, 218));
        jPanel4.setMinimumSize(new java.awt.Dimension(320, 270));
        jPanel4.setPreferredSize(new java.awt.Dimension(320, 270));
        jPanel4.setLayout(new java.awt.GridLayout());

        Label_Name.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        Label_Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Name.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel4.add(Label_Name);

        PanelPreview.add(jPanel4);

        getContentPane().add(PanelPreview);

        PanelSelect.setMinimumSize(new java.awt.Dimension(640, 540));
        PanelSelect.setPreferredSize(new java.awt.Dimension(640, 540));
        PanelSelect.setLayout(new javax.swing.BoxLayout(PanelSelect, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setMinimumSize(new java.awt.Dimension(640, 405));
        jPanel1.setPreferredSize(new java.awt.Dimension(640, 405));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        List_Employees.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 48)); // NOI18N
        List_Employees.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = employeeList;
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ScrollPane_Employees.setViewportView(List_Employees);

        jPanel1.add(ScrollPane_Employees);

        PanelSelect.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(114, 137, 218));
        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 32767));
        jPanel2.setMinimumSize(new java.awt.Dimension(640, 135));
        jPanel2.setPreferredSize(new java.awt.Dimension(640, 135));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        btnEdit.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setMaximumSize(new java.awt.Dimension(32767, 32767));
        btnEdit.setMinimumSize(new java.awt.Dimension(240, 50));
        btnEdit.setPreferredSize(new java.awt.Dimension(240, 50));
        jPanel2.add(btnEdit, new java.awt.GridBagConstraints());

        PanelSelect.add(jPanel2);

        getContentPane().add(PanelSelect);

        jMenuBar1.setMinimumSize(new java.awt.Dimension(56, 20));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(56, 20));
        jMenuBar1.setRequestFocusEnabled(false);

        MenuBack.setText("Back");
        jMenuBar1.add(MenuBack);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel Label_Name;
    private javax.swing.JLabel Label_ProfilePicture;
    private javax.swing.JList<String> List_Employees;
    private javax.swing.JMenu MenuBack;
    private javax.swing.JPanel PanelPreview;
    private javax.swing.JPanel PanelSelect;
    private javax.swing.JScrollPane ScrollPane_Employees;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
