/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;

import Runner.MainRunner;

import java.awt.Frame;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author Mason Smith
 */
@SuppressWarnings("serial")
public class ExtraMain extends javax.swing.JFrame {

    /**
     * Creates new form ExtraMain
     */
    public ExtraMain() {
    	setTitle("Extra");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	//sets the location of frame to middle of screen
    	GraphicsDevice gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
    	this.setLocation(gd.getDisplayMode().getWidth()/4-this.getSize().width/2, gd.getDisplayMode().getHeight()/4-this.getSize().height/2);
    	
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        PanelExtraBack = new javax.swing.JPanel();
        PanelExtraBack.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		MainRunner.runAdminMainGui();
        		//finds current frame out of listed frames and disposes of it
        		for(int i = 0; i < Frame.getFrames().length; i++) {
        			if(Frame.getFrames()[i].getTitle().equals("Extra")) {
        				Frame.getFrames()[i].dispose();
        			}
        		}
        	}
        });
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(960, 540));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane2.setToolTipText("");
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(960, 540));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(960, 540));

        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 540));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 540));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        PanelExtraBack.setBackground(new java.awt.Color(255, 255, 255));
        PanelExtraBack.setMinimumSize(new java.awt.Dimension(240, 540));
        PanelExtraBack.setPreferredSize(new java.awt.Dimension(240, 540));
        PanelExtraBack.setLayout(new GridLayout(0, 1, 0, 0));

        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel1.setIcon(new ImageIcon(ExtraMain.class.getResource("/Resources/back-button-icon.png")));
        PanelExtraBack.add(jLabel1);

        jPanel1.add(PanelExtraBack);

        jPanel3.setBackground(new java.awt.Color(153, 170, 181));
        jPanel3.setMinimumSize(new java.awt.Dimension(240, 540));
        jPanel3.setPreferredSize(new java.awt.Dimension(240, 540));
        jPanel3.setLayout(new GridLayout(0, 1, 0, 0));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new ImageIcon(ExtraMain.class.getResource("/Resources/edit-employee-icon.png"))); // NOI18N
        jPanel3.add(jLabel2);

        jPanel1.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setMinimumSize(new java.awt.Dimension(240, 540));
        jPanel4.setPreferredSize(new java.awt.Dimension(240, 540));
        jPanel4.setLayout(new GridLayout(0, 1, 0, 0));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/add-workinprogress-icon.png"))); // NOI18N
        jPanel4.add(jLabel3);

        jPanel1.add(jPanel4);

        jPanel9.setBackground(new java.awt.Color(153, 170, 181));
        jPanel9.setMinimumSize(new java.awt.Dimension(240, 540));
        jPanel9.setPreferredSize(new java.awt.Dimension(240, 540));
        jPanel9.setLayout(new GridLayout(0, 1, 0, 0));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/add-workinprogress-icon.png"))); // NOI18N
        jPanel9.add(jLabel4);

        jPanel1.add(jPanel9);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setMinimumSize(new java.awt.Dimension(240, 540));
        jPanel12.setPreferredSize(new java.awt.Dimension(240, 540));
        jPanel12.setLayout(new GridLayout(0, 1, 0, 0));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/add-workinprogress-icon.png"))); // NOI18N
        jPanel12.add(jLabel5);

        jPanel1.add(jPanel12);

        jScrollPane2.setViewportView(jPanel1);

        getContentPane().add(jScrollPane2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel PanelExtraBack;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
