/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.Color;

/**
 *
 * @author Mason Smith
 */
@SuppressWarnings("serial")
public class WorkOrderMultiPartSelect extends javax.swing.JFrame {

	public int count = 0;
	
    /**
     * Creates new form workOrderMutliPartSelect
     */
    public WorkOrderMultiPartSelect() {
    	setTitle("MultiPartSelect");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ButtonSubmit = new java.awt.Button();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuAdd = new javax.swing.JMenu();
        MenuRemove = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 400));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setMinimumSize(new java.awt.Dimension(800, 300));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 300));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setMinimumSize(new java.awt.Dimension(800, 300));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(800, 300));

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.PAGE_AXIS));

        

        jPanel6.add(createPanel(count));

        jScrollPane2.setViewportView(jPanel6);

        jPanel1.add(jScrollPane2);

        getContentPane().add(jPanel1);

        jPanel2.setMinimumSize(new java.awt.Dimension(800, 80));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 80));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        ButtonSubmit.setLabel("Submit");
        ButtonSubmit.setMinimumSize(new java.awt.Dimension(125, 30));
        ButtonSubmit.setPreferredSize(new java.awt.Dimension(125, 30));
        jPanel2.add(ButtonSubmit, new java.awt.GridBagConstraints());
        ButtonSubmit.getAccessibleContext().setAccessibleName("button_Submit");

        getContentPane().add(jPanel2);

        jMenuBar1.setMinimumSize(new java.awt.Dimension(800, 20));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(800, 20));

        MenuAdd.setText("Add");
        jMenuBar1.add(MenuAdd);

        MenuRemove.setText("Remove");
        jMenuBar1.add(MenuRemove);

        setJMenuBar(jMenuBar1);
        
        MenuAdd.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		jPanel6.add(createPanel(count));
        	}
        });
        
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public javax.swing.JPanel createPanel(int count){
//        javax.swing.JPanel jPanel3 = new JPanel();
//        jPanel3.setName(String.valueOf(count));
//        java.awt.Color color = new java.awt.Color(((int)(Math.random() * ((225 - 0) + 1)) + 0),((int)(Math.random() * ((225 - 0) + 1)) + 0),((int)(Math.random() * ((225 - 0) + 1)) + 0));
//        jPanel3.setBackground(color);
//        jPanel3.setMinimumSize(new java.awt.Dimension(800, 100));
//        jPanel3.setPreferredSize(new java.awt.Dimension(800, 100));
//        
//        
//        JLabel lblNewLabel;     
//        lblNewLabel = new JLabel(String.valueOf(count));
//        lblNewLabel.setHorizontalAlignment(SwingConstants.CENTER);
//        jPanel3.add(lblNewLabel);
    	
    	javax.swing.JPanel PanelDefault = new JPanel();
        javax.swing.JPanel PanelDescription = new JPanel();
        javax.swing.JPanel PanelPart = new JPanel();
        javax.swing.JScrollPane ScrollPaneDescription = new JScrollPane();
        javax.swing.JTextArea TextAreaDescription = new JTextArea();
        javax.swing.JTextField TextFieldPart = new JTextField();
        
        PanelDefault.setName(String.valueOf(count));

        java.awt.Color color = new java.awt.Color(((int)(Math.random() * ((225 - 0) + 1)) + 0),((int)(Math.random() * ((225 - 0) + 1)) + 0),((int)(Math.random() * ((225 - 0) + 1)) + 0));
        PanelDefault.setMinimumSize(new java.awt.Dimension(800, 100));
        PanelDefault.setBorder(BorderFactory.createLineBorder(Color.black));
        PanelDefault.setPreferredSize(new java.awt.Dimension(800, 100));
        PanelDefault.setLayout(new java.awt.GridLayout());

        PanelPart.setLayout(new java.awt.GridBagLayout());

        TextFieldPart.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        TextFieldPart.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldPart.setText("A");
        TextFieldPart.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TextFieldPart.setPreferredSize(new java.awt.Dimension(240, 30));
        PanelPart.add(TextFieldPart, new java.awt.GridBagConstraints());

        PanelDefault.add(PanelPart);

        PanelDescription.setLayout(new javax.swing.BoxLayout(PanelDescription, javax.swing.BoxLayout.LINE_AXIS));

        ScrollPaneDescription.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        TextAreaDescription.setColumns(20);
        TextAreaDescription.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        TextAreaDescription.setRows(5);
        ScrollPaneDescription.setViewportView(TextAreaDescription);
        PanelDescription.add(ScrollPaneDescription);
        PanelDefault.add(PanelDescription);
        
        jPanel6.revalidate();
        
        count++;
        
        return PanelDefault;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button ButtonSubmit;
    private javax.swing.JMenu MenuAdd;
    private javax.swing.JMenu MenuRemove;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
